name: Generate Breakout SVG

on:
  schedule:
    - cron: "0 0 * * *" # Simplified to run daily at midnight UTC
  workflow_dispatch:
    push: # Run on push to main branch
    branches:
      - main

jobs:
  generate-svg:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate SVG
        uses: cyprieng/github-breakout@v1.0.0
        with:
          github_username: ${{ github.repository_owner }}
          enable_ghost_bricks: True

      - name: Move generated SVGs
        run: |
          mkdir -p images
          [ -f output/light.svg ] && mv output/light.svg images/breakout-light.svg || echo "light.svg not found"
          [ -f output/dark.svg ] && mv output/dark.svg images/breakout-dark.svg || echo "dark.svg not found"

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push SVGs
        run: |
          git add images/breakout-light.svg images/breakout-dark.svg
          git commit -m "chore: update breakout SVGs" && git push || echo "No changes to commit"
